---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
  labels:
    app: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book-ms
          image: itsmedigio/book:1.0-SNAPSHOT
          ports:
          - containerPort: 8102
          volumeMounts:
          - mountPath: /app/config
            readOnly: true
            name: book-conf
      volumes:
      - name: book-conf
        configMap:
          name: book-conf
          items:
            - key: application.properties
              path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: book
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32102
      port: 8102
      targetPort: 8102
  selector:
    app: book